[package]
name = "vst-abstraction"
version = "0.1.0"
edition = "2021"

[features]
default = ["debug"]
debug = []

[dependencies]
nih_plug = {path = "../nih-plug"}
nih_plug_vizia = {path = "../nih-plug/nih_plug_vizia"}
image = {version = "0.24.6", default-features = false, features = ["png"]}

serde = { version = "1.0", features = ["derive"] }

# rand = "0.9.0"

[workspace]
members = ["xtask"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]


