name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run bundler
      run: |  
        export MACOSX_DEPLOYMENT_TARGET=10.13
        cargo xtask bundle-universal crunchy-plugin --release
    - uses: actions/upload-artifact@v4
      with:
        name: macos_build
        path: target/bundled/*
        if-no-files-found: warn
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: ConorMacBride/install-package@v1.1.0
      with:
        apt: libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxkbcommon-x11-dev libatk1.0-dev build-essential libgtk-3-dev libxcb-dri2-0-dev libxcb-icccm4-dev libx11-xcb-dev
    - uses: actions/checkout@v3
    - name: Run bundler
      run: cargo xtask bundle crunchy-plugin --profile release
    - uses: actions/upload-artifact@v4
      with:
        name: linux_build
        path: target/bundled/*
        if-no-files-found: warn
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run bundler
      run: cargo xtask bundle crunchy-plugin --profile release
    - uses: actions/upload-artifact@v4
      with:
        name: windows_build
        path: target/bundled/*
        if-no-files-found: warn
