name: build

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run bundler
      run: |  
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin
        
        export MACOSX_DEPLOYMENT_TARGET=10.13
        cargo xtask bundle-universal crunchy-plugin --release
    - uses: actions/upload-artifact@v4
      with:
        name: macos_build
        path: target/bundled/*
        if-no-files-found: warn

