name: test_mac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  test_mac:
    runs-on: macos-latest
    steps:
       
    - name: Download necessary software
      run: |
        curl -L https://github.com/Garneek/crunchy/releases/download/v.0.2.0/crunchy-vst3-macos.zip > macos_build.zip
        unzip macos_build.zip
        
        # Download Carla
        curl -L https://github.com/falkTX/Carla/releases/download/v2.5.9/Carla-2.5.9-macOS-universal.dmg > Carla.dmg
        
        # Mount image and copy App file
        hdiutil attach Carla.dmg
        cp -r /Volumes/Carla-2.5.9-universal/Carla.app .
        
        # Download Jack
        curl -L https://github.com/jackaudio/jack2-releases/releases/download/v1.9.22/jack2-macOS-universal-v1.9.22.tar.gz > Jack.tar.gz
        
        # Unpack Jack
        tar -xzvf Jack.tar.gz

        # Install Jack
        sudo installer -pkg jack2-osx-1.9.22.pkg -target /
        
    - name: Run tests
      run: |
        brew  install --cask xquartz
      
        #ls -R
        #QjackCtl.app/Contents/MacOS/QjackCtl -v
      
        # Start Jack
        QjackCtl.app/Contents/MacOS/QjackCtl -s &
        
        sleep 15
        
        # Start Carla with timeout of 10s
        Carla.app/Contents/MacOS/carla-bridge-native vst3 crunchy-plugin.vst3 label > log.txt 2>&1 & sleep 10; kill $!
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: macos_test_results
        path: log.txt
        if-no-files-found: warn
